version: '3.8'

services:
  todoapi:
    build:
      context: .
      dockerfile: TodoApi/Dockerfile
    ports:
      - "5041:80"
      - "7041:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80;https://+:443
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro 