name: CheckService

on: push 

jobs:
    lint:
        runs-on: self-hosted
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            
            - name: Проверка версии .NET
              run: dotnet --version

            - name: Install .NET 9.0 SDK
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: 9.0.x

            - name: install deps
              run: dotnet restore 
    test:
        runs-on: self-hosted
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            
            - name: Проверка версии .NET
              run: dotnet --version

            - name: install deps
              run: dotnet restore 

            - name: run tests
              run: dotnet test --verbosity normal