name: CheckService

on: push 

jobs:
    lint:
        runs-on: self-hosted
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            
            - name: Проверка версии .NET
              run: dotnet --version

            - name: install deps
              run: dotnet restore 
    test:
        needs: [lint]
        runs-on: self-hosted
        steps:
            - name: run tests
              run: dotnet test --verbosity normal
    scret:
        runs-on: self-hosted
        steps: 
            - name: Print secret
              run: echo ${{ secrets.SECRET }}
            
                