name: CheckService

on: push 

jobs:
    lint:
        runs-on: self-hosted
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: install deps
              run: dotnet restore 